#!/bin/bash

read $ttyn
ps -eo pid,command,tty,start_time --sort start_time | grep tty$ttyn | head -n -1 > ps_out_file

if [ -s ps_out_file ];
then
    cat ps_out_file
else
    echo Нет таких процессов
fi
